# Bun configuration for Trackivity v2

[install]
# Faster installs and more predictable dependency resolution
registry = "https://registry.npmjs.org/"
cache = true
exact = false
peer = true
dev = true
optional = true
frozenLockfile = false
dryRun = false

[install.scopes]
# Use specific registries for scoped packages if needed
# "@company" = "https://npm.company.com/"

[run]
# Development server configuration
shell = true
silent = false

[test]
# Testing configuration
coverage = false
bail = 0
timeout = 5000
preload = []

# Environment-specific overrides
[env]
NODE_ENV = "development"