version: '3.8'

services:
  backend:
    image: ghcr.io/akephisit/trackivity-backend:latest
    container_name: trackivity-backend
    restart: always
    environment:
      # Database Connection String form Managed Service (e.g. Neon)
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
      VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY}
      VAPID_PRIVATE_KEY: ${VAPID_PRIVATE_KEY}
      VAPID_SUBJECT: ${VAPID_SUBJECT:-mailto:admin@utrackivity.com}
      RUST_LOG: info
    ports:
      - "80:3000"
    # No dependency on local DB

# Removed volumes section as we don't need persistent storage for DB anymore
